### ISSUE TITLE
SF iOS Workshop for Women (25-Apr-2015)

### ISSUE THREAD

**Issue by kmolo** [mobilebridge/organizing#4] opened 2015-01-28 13:15 UTC
Let's get the ball rolling for our next SF iOS workshop -- here's what we need to do!

A few months out:
- [x] Find a venue and sponsor for the workshop. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop. Space-wise, we usually split the students up into separate class levels, so having access to multiple workspaces would be nice (and if possible, projectors & whiteboards).  Additionally, we like to offer students the option to bring their children with them (we recruit additional volunteers to help supervise so the parents can focus on coding).
  - [PlanGrid](http://www.plangrid.com/en/about) (~~@xenadu~~ @russbishop) has offered to host/sponsor.
  - Dates:
    - __Teacher Training__: Sun Apr 19th 4-7:30pm
    - __InstallFest__: Fri Apr 24th 6:30-7:30pm
    - __Workshop__: Sat Apr 25th 9am-5pm
- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
  - @kmolo and @jeffreybergier have volunteered to co-organize this workshop
- [x] Select the target student population for the workshop. Our workshops reach out to groups of people that are underrepresented in the community. That might be women, people of color, non-native English speakers, LGBQA communities, or other marginalized groups.
  - this iteration will be 'for women (cis- and trans-inclusive) and their guests'

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
  - 45 students
- [x] Review and, if necessary, revise the computer setup instructions (newer versions, etc)
- [x] Post the workshop to [Bridge Troll](https://www.bridgetroll.org/events/159)
  - [https://www.bridgetroll.org/events/159](https://www.bridgetroll.org/events/159)

One to two weeks out, we can:
- [x] Plan a Teacher Training
  - Sun 4/19 4-7:30pm at PlanGrid
- [x] Plan InstallFest 
  - Fri 4/24 6:30-7:30pm at PlanGrid
- [x] Order breakfast
- [x] Order lunch
- [x] Find a good place for the afterparty

After the workshop, we can:
- [x] Party! :tada:   
- [x] Retro
- [ ] Write a blog post

:tulip:

**Comment by kmolo** [comment] 2015-01-28 13:31
@moshi-kibu @timothy1ee @ultrasaurus @LauraKirby @mmesarina @StephanieSzeto @tjgrathwell @imju @steffi06 @stansey @nesquena @yskamoona @jeffreybergier @mtitolo @mludowise @shawnyapa @aparnarsjain @joekim @rajatb @dvidsilva

Getting the ball rolling for our next iOS workshop in SF.  Looking for everything:

 - 2 co-organizers
 - a venue/sponsor, ideally the same organizations (for simplicity), best not an organizer (for sanity)

Anyone interested in organizing the next workshop?
Does anyone know a company which would be interested in hosting/sponsoring (possibly their own)?

**Comment by kmolo** [comment] 2015-01-28 14:08
- By this weekend, I will write up & post the instructor debrief from [last workshop](https://github.com/mobilebridge/organizing/issues/3) (Dec 2014)
- @glenna, do you or someone else have the student debrief?

Two important things from the instructor debrief that jump out right now:
- our [Setup Instructions](https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites) are missing an essential setup command for cocoapods that comes after 'gem install cocoapods'
  - @mtitolo, you knew what this missing command was; would you add this final command to the [Setup Instructions](https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites)?
- the instructors wanted to modify the curriculum so only a single app would be taught -- the To-Do app for beginning class levels, the Rotten Tomatoes app for the more advanced levels -- instead of trying to rush through 2 apps

**Comment by glenna** [comment] 2015-01-28 17:32
I talked to Twitter, but need to reconnect. I would not be able to be an organizer in SF for a while. Moving to Berlin on Friday! But, I'm willing to help remotely in any way possible (even if it's just helping get new organizers up to speed).

@kmolo I'll share the google doc with the student responses

**Comment by xenadu** [comment] 2015-01-28 19:53
@kmolo PlanGrid can host and/or sponsor. For an event, I think 40 would probably be a good max. We don't have many big conference rooms but our space is cleanly divided in two so it would work well for splitting up skill levels. I'll email about it.

**Comment by kmolo** [comment] 2015-01-30 01:18
@xenadu great!

We'll pick a time via email when I can visit your office this week or next, and then we can report back about the spaces, and start the discussion about number of separate class levels possible, total number of students & instructors, etc.

**Comment by kmolo** [comment] 2015-01-30 01:20
@glenna what an exciting adventure!  Are you there for 6 months?

**Comment by xenadu** [comment] 2015-02-10 01:01
@kmolo Confirmed with the team here that PlanGrid wants to host and sponsor for up to 40 people. We may need one or two volunteers to help setup/teardown. Currently thinking Apr 24-25, but this far out our calendar is very flexible so we can move the date no problem. 

 I am happy to TA or teach if needed, I believe @gwendolynw was also interested. 

Just let us know what info we need to proceed.

**Comment by mfjenn** [comment] 2015-02-10 03:56
@glenna, We DEFINITLEY could use more organizer mentors. I did it for a while but have kind of fallen off the radar. It’s a great way to support the growth of the Bridges in a big way, is less work than actually organizing an event, and it’s very rewarding helping someone launch an event. 

Ping me off thread if you want to know about my experience in with mentoring.

**Comment by kmolo** [comment] 2015-02-10 10:24
@mtitolo thanks for updating our CocoaPods installation instructions

**Comment by kmolo** [comment] 2015-02-10 10:34
@xenadu @gwendolynw great news!

--------------------------
RE: date
I've created a Doodle poll to see if any of the previous instructors/volunteers can make that weekend:

http://doodle.com/4bnq5vynngvwc4rk
[ if anyone can't make that weekend, please post a comment in the poll suggesting alternate dates ]

--------------------------
RE: childcare
What we hope to offer is a "supervised play" area. Parents are nearby and ultimately responsible for their kids; we would be using experienced babysitters / trusted volunteers, not professional child care with all that implies. [ @xenadu I think you indicated that your wife might come & bring your little ones too. ]

Here's the existing waiver that we ask parents to sign if they bring their children with them:

http://tiny.cc/MB-parent-waiver

Anecdotally from Railsbridge's more extensive experience (Railsbridge is the spawning organization for a number of other *Bridges including MobileBridge), few people will bring kids, but knowing it is available will often allow parents to immediately RSVP, even if later a partner can take the kids.  More frequently, nursing/pumping space is needed.

**Comment by kmolo** [comment] 2015-02-12 10:11
*bump

Are the proposed installfest & workshop dates -- Fri 4/24 & Sat 4/25 -- good for you?
[PlanGrid folks assumed to be available since they picked the dates]

http://doodle.com/4bnq5vynngvwc4rk

Please participate by this Fri 2/13 by 5pm.  Thanks!

**Comment by xenadu** [comment] 2015-02-12 18:04
Some of the small conference rooms have privacy screens, comfy chairs, and can darken the lights so they should make good nursing spaces.

**Comment by kmolo** [comment] 2015-02-15 10:52
I want to announce that @jeffreybergier has agreed to co-organize this workshop.

Additionally, we’ve had enough instructors agree that they’re available, so we’ll go ahead & confirm the dates for this workshop as Fri Apr 24th (InstallFest) & Sat Apr 25th (Workshop).

Here are the debriefs from the first two iterations of this workshop:

http://tinyurl.com/MB-iOS-debriefs

Based on this feedback, here’s what we’re thinking of:

* Only doing 1 app on the day of the workshop, so everyone doesn’t feel so rushed.  

>QUESTION: Which app should the new-to-programming group work on? Should they jump right into RottenTomatoes, immediately using an API?  Or stay with the ToDo app, and be introduced to APIs (where to find them, how to use them, etc) at the end of the day?  

>> Possibly all students could be provided with the ToDo app as part of the references materials that they might look over before the workshop.

* We’re going to do another in-person InstallFest on Fri Apr 24th (likely 6:30-7:30pm, but to-be-confirmed with PlanGrid).
  * But also offer the option of completing a \*virtual* installation checkout via email prior to the InstallFest (if not completed beforehand, in-person InstallFest is still required).  
    * Here's the initial pass at the instructions of what to email, appended to the bottom of the existing Setup Instructions:  [https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites#installation-checkout-via-email](https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites#installation-checkout-via-email)

* And we're still continuing to build out the MobileBridge iOS curriculum:
  * Reference materials: 
    * basics required every time when creating an iOS app, 
    * an XCode tour (various windows, how to debug, etc),
    * Objective-C tutorial (basic, and then where to deep dive), 
    * links to the CodePath guides, 
    * overview of mobile applications, 
    * translation glossary relating Objective-C concepts to concepts from other languages/tools, 
    * where find out about & use popular APIs, 
    * how to install & use libraries, etc

Your thoughts? 
Your favorite reference sites? 
Anyone want to volunteer to create a wiki page for any of the proposed reference materials?

**Comment by kmolo** [comment] 2015-02-23 12:26
Hi everyone, I'll be offline until 3/7 (a little traveling).  Just wanted to let you know, so you wouldn't think I was being unresponsive.  

/cc @jeffreybergier @xenadu

**Comment by jeffreybergier** [comment] 2015-02-23 17:39
@kmolo have a good trip!

**Comment by xenadu** [comment] 2015-03-23 21:40
@kmolo @jeffreybergier @gwengrid I have us down for 6:30-7:30pm on Friday, then 9am-5pm on Saturday. Is that what we want to go with?

**Comment by kmolo** [comment] 2015-03-24 05:50
@xenadu that sounds good for InstallFest & Workshop.

We might have discussed this briefly, but I think we should do a separate teacher training:
+ for the [first workshop](https://www.bridgetroll.org/events/120), we did a Sunday 2 weeks before from 3-7pm;
+ for the [second workshop](https://www.bridgetroll.org/events/132), the Tuesday before the workshop from 6:30-9pm

What are everyone's thoughts about scheduling a teacher training? Which is a separate question from whether PlanGrid can host/sponsor this training.

**Comment by kmolo** [comment] 2015-03-24 05:51
I'm almost done writing up the BridgeTroll event details, so once we decide the if/when question for Teacher Training, I'll post it up.

**Comment by kmolo** [comment] 2015-04-02 03:03
Hi everyone, 

I've created a doodle poll to schedule a teacher training:

http://doodle.com/74p2q99zz7zsb2c5

Please fill in your available times in the next 24hrs. Then we'll be creating the BridgeTroll listing, so we can confirm/recruit instructors and publicize the workshop to students.

@xenadu @gwengrid let us know if the teacher training can take place at PlanGrid.

Thanks everyone!

//cc @dvidsilva @devhut @imju @jeffreybergier @mludowise @shawnyapa

**Comment by xenadu** [comment] 2015-04-02 23:44
@kmolo we should be able to host it.

**Comment by kmolo** [comment] 2015-04-03 00:04
@xenadu, great news!  If you and @gwengrid would complete the [teacher training scheduling doodle](http://doodle.com/74p2q99zz7zsb2c5) with the days on which both you & PlanGrid's office would be available, that would be awesome!

**Comment by shawnyapa** [comment] 2015-04-03 00:11
I have a friend who wants to sign up for the Class but I don't see it on
BridgeTroll yet.
Is signup posted somewhere else or has it just not been announced yet?

thanks!
-shawn y

**Comment by kmolo** [comment] 2015-04-03 00:22
@shawnyapa once we select the teacher training session, I'll post the whole set as a single workshop on BridgeTroll, so you're friend will be able to see it & sign up by this weekend.

Going forward, I think teacher trainings may be separate from installfest-workshops since we're starting to have a pool of instructors who have taught before, so we can decouple teacher trainings from workshops.

**Comment by shawnyapa** [comment] 2015-04-03 00:25
Perfect.
Thanks!

**Comment by kmolo** [comment] 2015-04-04 21:28
Our bridgetroll event is live:

https://www.bridgetroll.org/events/159

...and we've picked a Teacher Training time:

    Sun 4/19 4-7:30pm at PlanGrid (454 Shotwell St, San Francisco)

If you can be an instructor/TA, please sign up before the end of the weekend, so we know how many more instructors we'll need to recruit.

**Comment by kmolo** [comment] 2015-04-05 06:01
@xenadu if you & @gwengrid register on bridgetroll, then I can elevate you to organizers:

https://www.bridgetroll.org/events/159

...so you can see dietary needs for ordering food and other such things.

**Comment by kmolo** [comment] 2015-04-08 04:28
I'm on the Android side of the MobileBridge house, so putting out the call to @jeffreybergier and other iOS devs:

Time to see if we need to update the [Setup Instructions](https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites) as students are starting to complete the [installation checkout via email](https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites#installation-checkout-via-email).

- There's a new version of [Xcode](https://developer.apple.com/xcode/downloads/) -- 6.2 -- updated as of Mar 9, 2015. That's pretty new, but that's the stable version that the [https://developer.apple.com/xcode/downloads/](https://developer.apple.com/xcode/downloads/) link is offering.  
  - Is this version something that we want to encourage students to download, or do we want them to keep using Xcode 6.1.1 for now?
  - Is Xcode 6.2 necessary for developing for Apple Watch, or can Apple Watch apps be developed on older Xcode versions by sourcing the iOS 8.2 SDK?

Anything else we need to update in the [Setup Instructions](https://github.com/mobilebridge/iosbridge/wiki/Student-Prerequisites)?

**Comment by shawnyapa** [comment] 2015-04-08 16:25
I use Xcode 6.2 everyday and haven't had any real problems. I'd say it's
stable and perfectly acceptable for the class.
Yes, you're correct that you can only do watch development with Xcode 6.2
regardless if you're using iOS 8.2 in the simulator or otherwise.

The setup instructions look correct to me although they don't reference
Xcode 6.2 yet. I do remember some step missing in the cocoapod instructions
in last workshop in December although the detail is escaping me.

Hope that helps!
-shawn

**Comment by jeffreybergier** [comment] 2015-04-08 16:32
I haven't finished the curriculum yet, but cocoa pods won't be needed. I was just going to use NSURLSession instead of AFNetworking.

Also, if we're doing Objective C, Xcode 6 or higher is fine. If swift, 6.1.1 or higher is recommended. Generally, its just best to always have the newest version of Xcode.

**Comment by xenadu** [comment] 2015-04-08 18:31
FYI: Xcode 6.3 is going live on the app store today (but isn't available as of this moment) so anyone attempting to install will end up with that version. Might want to require 6.3... I've been using the beta releases and haven't run into any major issues.

**Comment by jeffreybergier** [comment] 2015-04-08 18:33
Perhaps. Since we're doing it in Objective C, I don't think it will be much of an issue. 

If we do Swift then its a really big deal. Xcode 6.3 introduces a new version of Swift that is source code incompatible the old version of swift. So a swift project made in 6.2 will likely not compile in 6.3. Same for teaching, if students have mixed versions. It could be really tough.

**Comment by kmolo** [comment] 2015-04-16 20:53
Request from @jeffreybergier:

> I’m about half way done with material for instructors for @mobilebridgesf in 2 weeks. Looking for feedback :)

https://github.com/jeffreybergier/RottenTomatoesGuide/wiki

(on Twitter, in case you want to share with other iOS folks)
https://twitter.com/jeffburg/status/588588119252828161

**Comment by ultrasaurus** [comment] 2015-04-18 09:27
Katherine Moloney (is the @kmolo ?) reached out via email and I said I would teach the same class that Tim Lee taught and I TA'd at the very first workshop, based on CodePath's iOS for Designers curriculum.

To prepare for that, @stansey and I have been working on a [prototyping curriculum](https://github.com/stansey/prototyping-curriculum) for next week's workshop.  Following @jeffreybergier lead, I opened  https://github.com/mobilebridge/iosbridge/issues/6 for feedback.

Aside from wanting to help MobileBridge in any way I can,  I'm also motivated to hone my somewhat weak iOS skillz.  Sara can't make it to teacher training tomorrow, but said she would TA with me.  I would really, really appreciate a couple more expert iOS developers who would be interested in TA-ing this session.  I think it is a great approach for people with zero coding experience, but I think it might be fun for expert coders who want to focus on XCode and/or learn prototyping techniques.

**Comment by ultrasaurus** [comment] 2015-04-19 23:12
teacher training:  https://docs.google.com/document/d/15UY9pYuCCPqc3eMl3x19OkmhyGawgcYzGHxUl0gwoos/edit

**Closed** 2015-05-22 08:33 UTC

**Comment by kmolo** [comment] 2015-10-02 02:18
@jeffreybergier @ultrasaurus @russbishop do have or know who led / has the instructor debrief from this Apr-2015 iOS workshop at PlanGrid?

I'm working on getting the student debrief for this workshop written up & shared:

http://tinyurl.com/MB-iOS-debriefs 

...along with the student debrief for the latest Sep-2015 workshop (#9).  Ideally will be able to share all the debriefs with organizers of the upcoming Dec-2015 workshop (#14) by next week (they're really making progress, and I don't want to slow them down).

**Comment by jeffreybergier** [comment] 2015-10-02 02:22
@kmolo I have the feedback from the volunteers. I'll try to get it written up this weekend.

**Comment by kmolo** [comment] 2015-10-02 02:32
Excellent!  You have both the missing volunteer debriefs & I have both the missing student debrief.  After this weekend, all the debriefs will be available to the upcoming organizers.
